// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkpyypoaqwlxnkfmicvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrcHl5cG9hcXdseG5rZm1pY3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzI3MTQsImV4cCI6MjA2MDc0ODcxNH0.Cnjv8Bl6-378cADLQ9rkn3EgUkH3wW9ZPrFxFrb_PFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);